kind: DNSChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: {}
spec:
  action: random
  mode: all
  selector:
    namespaces:
      - {}
    labelSelectors:
      name: {}
  patterns:
    - {}
  duration: {}