kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: {}
spec:
  mode: all
  selector:
    namespaces:
      - {}
    labelSelectors:
      name: {}
  target: {} # Request
  port: {} # 80
  method: {} # GET
  path: {} # /api
  delay: {} # 10s
  duration: {} # 5m