kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: {}
spec:
  action: duplicate
  mode: all
  selector:
    namespaces:
      - {}
    labelSelectors:
      name: {}
  duplicate:
    duplicate: {}
    correlation: {}
  direction: to
  duration: {}
  device: {}