kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: {}
spec:
  action: corrupt
  mode: all
  selector:
    namespaces:
      - {}
    labelSelectors:
      name: {}
  corrupt:
    corrupt: {}
    correlation: {}
  direction: to
  device: {}
  duration: {}