kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: {}
spec:
  selector:
    namespaces:
      - {}
    labelSelectors:
      name: {}
  mode: all
  action: loss
  loss:
    loss: {}
    correlation: {}
  direction: to
  duration: {}
  device: {}