trigger:
  branches:
    include:
      - main
      - master
      - chart-dev
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore
      - azure-pipelines.yml
      - apply.yaml
      - chaosd_install.sh

resources:
  - repo: self

pool: "Azure Pipelines"
#pool: "Default"

variables:
  image-repo: 'bupt2018/aiops-evaluation'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: '$(Build.BuildNumber)-$(SHORT_COMMIT)'
              Dockerfile: '**/Dockerfile'


          - script: |
              curl --location --request PUT --X PUT 'http://cd.bupt.site:30303/api/v1/deployments' --header 'Content-Type: application/json'  --header 'key: irvGAJSUaovNOtzUABshOqEgLvLhJesHAEgHOLoyMtQsnrrxrSHZlCjvuUQvtbpW'    --header 'value: token-anomaly-detection-evaluation-server-evaluation-server-0056f142'      --data '{ "namespace":"anomaly-detection","deployment":"evaluation-server","container": "evaluation-server","image": "registry.cn-beijing.aliyuncs.com/$(image-repo):$(Build.BuildNumber)-$(SHORT_COMMIT)"}'
            displayName: 'send curl'
