# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: netservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'netservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10netservice.proto\x12\nnetservice\"1\n\x0bInitRequest\x12\x0f\n\x07PodName\x18\x01 \x01(\t\x12\x11\n\tNamespace\x18\x02 \x01(\t\"\x80\x01\n\x0bMakeRequest\x12\x10\n\x08PodName1\x18\x01 \x01(\t\x12\x0f\n\x07IfName1\x18\x02 \x01(\t\x12\x0b\n\x03Ip1\x18\x03 \x01(\t\x12\x10\n\x08PodName2\x18\x04 \x01(\t\x12\x0f\n\x07IfName2\x18\x05 \x01(\t\x12\x0b\n\x03Ip2\x18\x06 \x01(\t\x12\x11\n\tNamespace\x18\x07 \x01(\t\"C\n\rDeleteRequest\x12\x0f\n\x07PodName\x18\x01 \x01(\t\x12\x0e\n\x06IfName\x18\x02 \x01(\t\x12\x11\n\tNamespace\x18\x03 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb9\x01\n\x05Local\x12\x38\n\x08InitLink\x12\x17.netservice.InitRequest\x1a\x11.netservice.Reply\"\x00\x12\x38\n\x08MakeLink\x12\x17.netservice.MakeRequest\x1a\x11.netservice.Reply\"\x00\x12<\n\nDeleteLink\x12\x19.netservice.DeleteRequest\x1a\x11.netservice.Reply\"\x00\x42\x0fZ\r./;netserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./;netservice'
  _globals['_INITREQUEST']._serialized_start=32
  _globals['_INITREQUEST']._serialized_end=81
  _globals['_MAKEREQUEST']._serialized_start=84
  _globals['_MAKEREQUEST']._serialized_end=212
  _globals['_DELETEREQUEST']._serialized_start=214
  _globals['_DELETEREQUEST']._serialized_end=281
  _globals['_REPLY']._serialized_start=283
  _globals['_REPLY']._serialized_end=307
  _globals['_LOCAL']._serialized_start=310
  _globals['_LOCAL']._serialized_end=495
# @@protoc_insertion_point(module_scope)
