# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import netservice_pb2 as netservice__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in netservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitLink = channel.unary_unary(
                '/netservice.Local/InitLink',
                request_serializer=netservice__pb2.InitRequest.SerializeToString,
                response_deserializer=netservice__pb2.Reply.FromString,
                _registered_method=True)
        self.MakeLink = channel.unary_unary(
                '/netservice.Local/MakeLink',
                request_serializer=netservice__pb2.MakeRequest.SerializeToString,
                response_deserializer=netservice__pb2.Reply.FromString,
                _registered_method=True)
        self.DeleteLink = channel.unary_unary(
                '/netservice.Local/DeleteLink',
                request_serializer=netservice__pb2.DeleteRequest.SerializeToString,
                response_deserializer=netservice__pb2.Reply.FromString,
                _registered_method=True)


class LocalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitLink': grpc.unary_unary_rpc_method_handler(
                    servicer.InitLink,
                    request_deserializer=netservice__pb2.InitRequest.FromString,
                    response_serializer=netservice__pb2.Reply.SerializeToString,
            ),
            'MakeLink': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeLink,
                    request_deserializer=netservice__pb2.MakeRequest.FromString,
                    response_serializer=netservice__pb2.Reply.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=netservice__pb2.DeleteRequest.FromString,
                    response_serializer=netservice__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netservice.Local', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netservice.Local', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Local(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netservice.Local/InitLink',
            netservice__pb2.InitRequest.SerializeToString,
            netservice__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netservice.Local/MakeLink',
            netservice__pb2.MakeRequest.SerializeToString,
            netservice__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netservice.Local/DeleteLink',
            netservice__pb2.DeleteRequest.SerializeToString,
            netservice__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
