apiVersion: v1
kind: Service
metadata:
  name: load-maker-master-ui
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

  selector:
    app: load-maker-master
---
apiVersion: v1
kind: Service
metadata:
  name: load-maker-master-5557
spec:
  selector:
    app: load-maker-master
  ports:
  - port: 5557
    targetPort: 5557
