# ALERT: DO NOT USE CTRL+L TO FORMAT THIS FILE.
# ALERT: DO NOT USE CTRL+L TO FORMAT THIS FILE.
# ALERT: DO NOT USE CTRL+L TO FORMAT THIS FILE.

kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: node-cpu-stress-792871f1-29e5-45b2-bf0e-f77aa2528a3e
spec:
  action: stress-cpu
  address:
    - http://192.168.31.25:31767
  mode: all
  stress-cpu:
    load: 80
    workers: 32
  duration: 1m