---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      tolerations:
        - key: "sockshop"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:0.3.12
#          image: front:nginx
          imagePullPolicy: IfNotPresent
          resources:
#            limits:
#              cpu: 300m
#              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8079
          env:
            - name: SESSION_REDIS
              value: "true"

          securityContext:
            runAsNonRoot: false
            runAsUser: 10001
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
          livenessProbe:
            httpGet:
              path: /
              port: 8079
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8079
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime

            - name: temp
              mountPath: /.npm

#      nodeSelector:
#        beta.kubernetes.io/os: linux
#        sockshop: "true"

      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

        - name: temp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: front-end
spec:
#  type: NodePort
  ports:
    - port: 80
      targetPort: 8079
#      nodePort: 30001
  selector:
    name: front-end