---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
    spec:
      tolerations:
        - key: "sockshop"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: payment

          image: weaveworksdemos/payment:0.4.3
          command: [ "/app" ]
          args: ["-port=80","-decline=999.9" ]
          imagePullPolicy: IfNotPresent
          resources:
#            limits:
#              cpu: 200m
#              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5

          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime

#      nodeSelector:
#        beta.kubernetes.io/os: linux
#        sockshop: "true"

      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: payment
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    name: payment