---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    name: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      name: shipping
  template:
    metadata:
      labels:
        name: shipping
    spec:
      tolerations:
        - key: "sockshop"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: shipping
          image: weaveworksdemos/shipping:0.4.8
          imagePullPolicy: IfNotPresent
          env:
            # - name: ZIPKIN
            #   value: zipkin-mongo.default.svc.cluster.local
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
#            limits:
#              cpu: 100m
#              memory: 800Mi
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - name: localtime
              mountPath: /etc/localtime

      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
#      nodeSelector:
#        beta.kubernetes.io/os: linux
#        sockshop: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: shipping
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    name: shipping